apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: testrun-after-cert-change
build:
  artifacts:
    - image: granatengeorg-de/testrun-after-cert-change
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}